// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package market

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6e040014DecodeDatabetGoSdkPkgMarket(in *jlexer.Lexer, out *jsonMarket) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "type_id":
			out.TypeID = int(in.Int())
		case "template":
			out.Template = string(in.String())
		case "status":
			out.Status = Status(in.Int())
		case "odds":
			(out.Odds).UnmarshalEasyJSON(in)
		case "specifiers":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Specifiers = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					v1 = string(in.String())
					(out.Specifiers)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "meta":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Meta = make(map[string]interface{})
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 interface{}
					if m, ok := v2.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v2.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v2 = in.Interface()
					}
					(out.Meta)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		case "flags":
			out.Flags = int(in.Int())
		case "is_robot_detached":
			out.IsRobotDetached = bool(in.Bool())
		case "is_defective":
			out.IsDefective = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6e040014EncodeDatabetGoSdkPkgMarket(out *jwriter.Writer, in jsonMarket) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type_id\":"
		out.RawString(prefix)
		out.Int(int(in.TypeID))
	}
	{
		const prefix string = ",\"template\":"
		out.RawString(prefix)
		out.String(string(in.Template))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Int(int(in.Status))
	}
	{
		const prefix string = ",\"odds\":"
		out.RawString(prefix)
		(in.Odds).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"specifiers\":"
		out.RawString(prefix)
		if in.Specifiers == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v3First := true
			for v3Name, v3Value := range in.Specifiers {
				if v3First {
					v3First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v3Name))
				out.RawByte(':')
				out.String(string(v3Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"meta\":"
		out.RawString(prefix)
		if in.Meta == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.Meta {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				if m, ok := v4Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v4Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v4Value))
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		out.Int(int(in.Flags))
	}
	{
		const prefix string = ",\"is_robot_detached\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsRobotDetached))
	}
	{
		const prefix string = ",\"is_defective\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDefective))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonMarket) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6e040014EncodeDatabetGoSdkPkgMarket(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonMarket) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6e040014EncodeDatabetGoSdkPkgMarket(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonMarket) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6e040014DecodeDatabetGoSdkPkgMarket(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonMarket) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6e040014DecodeDatabetGoSdkPkgMarket(l, v)
}
func easyjson6e040014DecodeDatabetGoSdkPkgMarket1(in *jlexer.Lexer, out *Collection) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(Collection)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v5 Market
			easyjson6e040014DecodeDatabetGoSdkPkgMarket2(in, &v5)
			(*out)[key] = v5
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6e040014EncodeDatabetGoSdkPkgMarket1(out *jwriter.Writer, in Collection) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v6First := true
		for v6Name, v6Value := range in {
			if v6First {
				v6First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v6Name))
			out.RawByte(':')
			(v6Value).MarshalEasyJSON(out)
		}
		out.RawByte('}')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Collection) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6e040014EncodeDatabetGoSdkPkgMarket1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Collection) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6e040014EncodeDatabetGoSdkPkgMarket1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Collection) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6e040014DecodeDatabetGoSdkPkgMarket1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Collection) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6e040014DecodeDatabetGoSdkPkgMarket1(l, v)
}
func easyjson6e040014DecodeDatabetGoSdkPkgMarket2(in *jlexer.Lexer, out *Market) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "type_id":
			out.TypeID = int(in.Int())
		case "template":
			out.Template = string(in.String())
		case "status":
			out.Status = Status(in.Int())
		case "odds":
			(out.Odds).UnmarshalEasyJSON(in)
		case "specifiers":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Specifiers = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v7 string
					v7 = string(in.String())
					(out.Specifiers)[key] = v7
					in.WantComma()
				}
				in.Delim('}')
			}
		case "meta":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Meta = make(map[string]interface{})
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v8 interface{}
					if m, ok := v8.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v8.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v8 = in.Interface()
					}
					(out.Meta)[key] = v8
					in.WantComma()
				}
				in.Delim('}')
			}
		case "flags":
			out.Flags = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6e040014EncodeDatabetGoSdkPkgMarket2(out *jwriter.Writer, in Market) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type_id\":"
		out.RawString(prefix)
		out.Int(int(in.TypeID))
	}
	{
		const prefix string = ",\"template\":"
		out.RawString(prefix)
		out.String(string(in.Template))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Int(int(in.Status))
	}
	{
		const prefix string = ",\"odds\":"
		out.RawString(prefix)
		(in.Odds).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"specifiers\":"
		out.RawString(prefix)
		if in.Specifiers == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v9First := true
			for v9Name, v9Value := range in.Specifiers {
				if v9First {
					v9First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v9Name))
				out.RawByte(':')
				out.String(string(v9Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"meta\":"
		out.RawString(prefix)
		if in.Meta == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v10First := true
			for v10Name, v10Value := range in.Meta {
				if v10First {
					v10First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v10Name))
				out.RawByte(':')
				if m, ok := v10Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v10Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v10Value))
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		out.Int(int(in.Flags))
	}
	out.RawByte('}')
}
