// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package market

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6e040014DecodeGithubComDatabetCloudDatabetGoSdkPkgMarket(in *jlexer.Lexer, out *Markets) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(Markets)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v1 Market
			(v1).UnmarshalEasyJSON(in)
			(*out)[key] = v1
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6e040014EncodeGithubComDatabetCloudDatabetGoSdkPkgMarket(out *jwriter.Writer, in Markets) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v2First := true
		for v2Name, v2Value := range in {
			if v2First {
				v2First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v2Name))
			out.RawByte(':')
			(v2Value).MarshalEasyJSON(out)
		}
		out.RawByte('}')
	}
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Markets) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6e040014EncodeGithubComDatabetCloudDatabetGoSdkPkgMarket(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Markets) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6e040014DecodeGithubComDatabetCloudDatabetGoSdkPkgMarket(l, v)
}
func easyjson6e040014DecodeGithubComDatabetCloudDatabetGoSdkPkgMarket1(in *jlexer.Lexer, out *Market) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "template":
			out.Template = string(in.String())
		case "status":
			out.Status = Status(in.Int())
		case "odds":
			(out.Odds).UnmarshalEasyJSON(in)
		case "type_id":
			out.TypeID = int(in.Int())
		case "specifiers":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Specifiers = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 string
					v3 = string(in.String())
					(out.Specifiers)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		case "is_defective":
			out.IsDefective = bool(in.Bool())
		case "meta":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Meta = make(map[string]interface{})
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v4 interface{}
					if m, ok := v4.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v4.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v4 = in.Interface()
					}
					(out.Meta)[key] = v4
					in.WantComma()
				}
				in.Delim('}')
			}
		case "flags":
			out.Flags = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6e040014EncodeGithubComDatabetCloudDatabetGoSdkPkgMarket1(out *jwriter.Writer, in Market) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"template\":"
		out.RawString(prefix)
		out.String(string(in.Template))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Int(int(in.Status))
	}
	{
		const prefix string = ",\"odds\":"
		out.RawString(prefix)
		(in.Odds).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"type_id\":"
		out.RawString(prefix)
		out.Int(int(in.TypeID))
	}
	{
		const prefix string = ",\"specifiers\":"
		out.RawString(prefix)
		if in.Specifiers == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v5First := true
			for v5Name, v5Value := range in.Specifiers {
				if v5First {
					v5First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v5Name))
				out.RawByte(':')
				out.String(string(v5Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"is_defective\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsDefective))
	}
	{
		const prefix string = ",\"meta\":"
		out.RawString(prefix)
		if in.Meta == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v6First := true
			for v6Name, v6Value := range in.Meta {
				if v6First {
					v6First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v6Name))
				out.RawByte(':')
				if m, ok := v6Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v6Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v6Value))
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"flags\":"
		out.RawString(prefix)
		out.Int(int(in.Flags))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Market) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6e040014EncodeGithubComDatabetCloudDatabetGoSdkPkgMarket1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Market) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6e040014DecodeGithubComDatabetCloudDatabetGoSdkPkgMarket1(l, v)
}
